import { DefineComponent } from 'vue'

export type Flag = DefineComponent<{title: string}>;

export const AC: Flag
export const AD: Flag
export const AE: Flag
export const AF: Flag
export const AG: Flag
export const AI: Flag
export const AL: Flag
export const AM: Flag
export const AO: Flag
export const AQ: Flag
export const AR: Flag
export const AS: Flag
export const AT: Flag
export const AU: Flag
export const AW: Flag
export const AX: Flag
export const AZ: Flag
export const BA: Flag
export const BB: Flag
export const BD: Flag
export const BE: Flag
export const BF: Flag
export const BG: Flag
export const BH: Flag
export const BI: Flag
export const BJ: Flag
export const BL: Flag
export const BM: Flag
export const BN: Flag
export const BO: Flag
export const BQ: Flag
export const BR: Flag
export const BS: Flag
export const BT: Flag
export const BV: Flag
export const BW: Flag
export const BY: Flag
export const BZ: Flag
export const CA: Flag
export const CC: Flag
export const CD: Flag
export const CF: Flag
export const CG: Flag
export const CH: Flag
export const CI: Flag
export const CK: Flag
export const CL: Flag
export const CM: Flag
export const CN: Flag
export const CO: Flag
export const CR: Flag
export const CU: Flag
export const CV: Flag
export const CW: Flag
export const CX: Flag
export const CY: Flag
export const CZ: Flag
export const DE: Flag
export const DJ: Flag
export const DK: Flag
export const DM: Flag
export const DO: Flag
export const DZ: Flag
export const EC: Flag
export const EE: Flag
export const EG: Flag
export const EH: Flag
export const ER: Flag
export const ES: Flag
export const ET: Flag
export const EU: Flag
export const FI: Flag
export const FJ: Flag
export const FK: Flag
export const FM: Flag
export const FO: Flag
export const FR: Flag
export const GA: Flag
export const GB: Flag
export const GD: Flag
export const GE: Flag
export const GF: Flag
export const GG: Flag
export const GH: Flag
export const GI: Flag
export const GL: Flag
export const GM: Flag
export const GN: Flag
export const GP: Flag
export const GQ: Flag
export const GR: Flag
export const GS: Flag
export const GT: Flag
export const GU: Flag
export const GW: Flag
export const GY: Flag
export const HK: Flag
export const HM: Flag
export const HN: Flag
export const HR: Flag
export const HT: Flag
export const HU: Flag
export const IC: Flag
export const ID: Flag
export const IE: Flag
export const IL: Flag
export const IM: Flag
export const IN: Flag
export const IO: Flag
export const IQ: Flag
export const IR: Flag
export const IS: Flag
export const IT: Flag
export const JE: Flag
export const JM: Flag
export const JO: Flag
export const JP: Flag
export const KE: Flag
export const KG: Flag
export const KH: Flag
export const KI: Flag
export const KM: Flag
export const KN: Flag
export const KP: Flag
export const KR: Flag
export const KW: Flag
export const KY: Flag
export const KZ: Flag
export const LA: Flag
export const LB: Flag
export const LC: Flag
export const LI: Flag
export const LK: Flag
export const LR: Flag
export const LS: Flag
export const LT: Flag
export const LU: Flag
export const LV: Flag
export const LY: Flag
export const MA: Flag
export const MC: Flag
export const MD: Flag
export const ME: Flag
export const MF: Flag
export const MG: Flag
export const MH: Flag
export const MK: Flag
export const ML: Flag
export const MM: Flag
export const MN: Flag
export const MO: Flag
export const MP: Flag
export const MQ: Flag
export const MR: Flag
export const MS: Flag
export const MT: Flag
export const MU: Flag
export const MV: Flag
export const MW: Flag
export const MX: Flag
export const MY: Flag
export const MZ: Flag
export const NA: Flag
export const NC: Flag
export const NE: Flag
export const NF: Flag
export const NG: Flag
export const NI: Flag
export const NL: Flag
export const NO: Flag
export const NP: Flag
export const NR: Flag
export const NU: Flag
export const NZ: Flag
export const OM: Flag
export const PA: Flag
export const PE: Flag
export const PF: Flag
export const PG: Flag
export const PH: Flag
export const PK: Flag
export const PL: Flag
export const PM: Flag
export const PN: Flag
export const PR: Flag
export const PS: Flag
export const PT: Flag
export const PW: Flag
export const PY: Flag
export const QA: Flag
export const RE: Flag
export const RO: Flag
export const RS: Flag
export const RU: Flag
export const RW: Flag
export const SA: Flag
export const SB: Flag
export const SC: Flag
export const SD: Flag
export const SE: Flag
export const SG: Flag
export const SH: Flag
export const SI: Flag
export const SJ: Flag
export const SK: Flag
export const SL: Flag
export const SM: Flag
export const SN: Flag
export const SO: Flag
export const SR: Flag
export const SS: Flag
export const ST: Flag
export const SV: Flag
export const SX: Flag
export const SY: Flag
export const SZ: Flag
export const TA: Flag
export const TC: Flag
export const TD: Flag
export const TF: Flag
export const TG: Flag
export const TH: Flag
export const TJ: Flag
export const TK: Flag
export const TL: Flag
export const TM: Flag
export const TN: Flag
export const TO: Flag
export const TR: Flag
export const TT: Flag
export const TV: Flag
export const TW: Flag
export const TZ: Flag
export const UA: Flag
export const UG: Flag
export const UM: Flag
export const US: Flag
export const UY: Flag
export const UZ: Flag
export const VA: Flag
export const VC: Flag
export const VE: Flag
export const VG: Flag
export const VI: Flag
export const VN: Flag
export const VU: Flag
export const WF: Flag
export const WS: Flag
export const XK: Flag
export const YE: Flag
export const YT: Flag
export const ZA: Flag
export const ZM: Flag
export const ZW: Flag